title: Afroze Khan
author: proxyroot
email: afroze@proxyroot.com
description: Everything you can learn from basics to advanced concepts. Build resilient applications at scale. Learning concepts and frameworks using python. Example frameworks such as aws, Django, pytest, freezegun, s3, moto, elasticsearch, restfull, drf, gcloud and more.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /:title/
texture:
  title: Afroze Khan
  tagline: Staff Engineer
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  analytics_id: UA-166504171-1

  # generate social links in footer
  social_links:
    twitter: proxyroot
    github:  proxyroot
    linkedIn: afroze-k-190180129

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- index.md
- about.md
- contact.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
